### ISSUE TITLE
To have configurable purgatory list url and dockerized image

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/market-purgatory#1]
To have configurable purgatory list url and dockered image for different environment.

There is 2 or more reference of purgatory json links were hardcoded, such as:
1. https://github.com/oceanprotocol/market-purgatory/blob/main/api/asset.ts
2. https://github.com/oceanprotocol/market-purgatory/blob/main/api/account.ts

To have: 
1. Purgatory list links configurable.
2. Solution dockerized, so we could just pull and deploy image to different environment easily.

**Comment by kremalicious** [comment]
this is not easily dockerizable and probably shouldn't as we rely on Vercel-specific functionality for [serverless functions](https://vercel.com/docs/serverless-functions/introduction). This is also no Ocean Protocol core component but, as the name suggests, just an extension of our own `market`.

What exactly is preventing you from forking this repo and deploy under your own Vercel account?

**Comment by soonhuat** [comment]
Because we have and deploy application on public github and hosting service.
I think we can figure out something to overcome this, thanks.
